version: "3.8"
services:
  postgres:
    build: ./postgres
    container_name: postgres
    volumes:
      - /tmp/pgsql/pg_data:/var/lib/postgresql/data
    env_file: .env
    expose:
      - 5432
    ports:
      - 5432:5432
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
  # APP*****************************************
  jwtapi:
    build: .
    networks:
      - default
    hostname: localhost
    ports:
      - 8080:8080
    depends_on:
      - postgres
    env_file: .env
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
networks:
  web:
    external: true
